### ISSUE TITLE
Simplified Component Example Not Working With CommonModule

### ISSUE THREAD

**Issue by johnjspiteri** [teambit/bit-angular#33]
I am migrating all our internal directives from NPM to Bit.

When I reference [ngClass] from the CommonModule in a template, I am getting an error in the "teambit.preview/preview:GeneratePreview" build task (env "teambit.angular/angular-v13@0.0.7").

Module
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { IASelectComponent } from './component';

@NgModule({
	declarations: [IASelectComponent],
	imports: [CommonModule],
	exports: [IASelectComponent],
})
export class IASelectModule {}
```

Component Template
```
template: `
	<h1 [ngClass]="{ active: true }">Testing</h1>
`
```
		
workspace.jsonc
```
"teambit.dependencies/dependency-resolver": {
	"packageManager": "teambit.dependencies/pnpm",
	"policy": {}
}
```

bit show select/option
```
id: interface-agency.directives/select/option@0.0.3
scope: interface-agency.directives
name: select/option
env: teambit.angular/angular-v13@0.0.7
deprecated: false
package name: @interface-agency/directives.select.option
main file: public-api.ts
files: public:
  -api.ts
  - src/component.ts
  - src/docs.md
  - src/module.ts
  - src/test.composition.ts
  
dev files: 
  - src/test.composition.ts (teambit.compositions/compositions)
  
extensions:
  - teambit.angular/angular-v13@0.0.7                          
  - teambit.component/dev-files                                
  - teambit.compositions/compositions                    
  - teambit.pkg/pkg                                             
  - teambit.docs/docs                                         
  - teambit.envs/envs                                           
  - teambit.dependencies/dependency-resolver                 
  - teambit.pipelines/builder                                  

dependencies:
  - @angular/forms@13.1.2- (package)                           
  - tslib@^2.3.0---------- (package)    
                       
dev dependencies:
  - @teambit/angular-v13@0.0.7---- (component)                  
  - @angular/core@13.1.1---------- (package)                    
  - jest-preset-angular@~11.0.1--- (package)                    
  - jest@^27.4.4------------------ (package)                    
  - @types/node@^12.11.1---------- (package)                    
  - @types/jest@^27.0.3----------- (package)                    
  - @angular/compiler-cli@~13.1.1- (package)                    
  - @angular/compiler@~13.1.1----- (package)                    

peer dependencies:
  - typescript@~4.5.2------------------------- (package)        
  - zone.js@~0.11.4--------------------------- (package)        
  - rxjs@~7.4.0------------------------------- (package)        
  - @angular/platform-browser-dynamic@~13.1.1- (package)        
  - @angular/platform-browser@~13.1.1--------- (package)        
  - @angular/common@~13.1.1------------------- (package)  
```

1. bit clear-cache
2. bit install 👍 
2. bit compile 👍 
3. bit start 👍 
4. bit tag select/option --log 👎 

bvm version: 0.0.30
bit version: 0.0.603
Angular version: angular-v13@0.0.7
node: v16.10.0

```
component: interface-agency.directives/select/option@0.0.4

✖ Total 6 tasks. 5 succeeded. 1 failed. 0 skipped. Total errors: 8.
    at TaskResultsList.throwErrorsIfExist (/Users/jj/.bvm/versions/0.0.603/bit-0.0.603/node_modules/@teambit/builder/dist/task-results-list.js:62:13)
    at BuilderMain.tagListener (/Users/jj/.bvm/versions/0.0.603/bit-0.0.603/node_modules/@teambit/builder/dist/builder.main.runtime.js:308:60)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async legacyOnTagFunc (/Users/jj/.bvm/versions/0.0.603/bit-0.0.603/node_modules/@teambit/scope/dist/scope.main.runtime.js:502:11)
    at async pMapSeries (/Users/jj/.bvm/versions/0.0.603/bit-0.0.603/node_modules/p-map-series/index.js:9:15)
    at async tagModelComponent (/Users/jj/.bvm/versions/0.0.603/bit-0.0.603/node_modules/@teambit/legacy/dist/scope/component-ops/tag-model-component.js:498:21)
    at async Consumer.tag (/Users/jj/.bvm/versions/0.0.603/bit-0.0.603/node_modules/@teambit/legacy/dist/consumer/consumer.js:1024:9)
    at async tagAction (/Users/jj/.bvm/versions/0.0.603/bit-0.0.603/node_modules/@teambit/legacy/dist/api/consumer/lib/tag.js:209:22)
    at async Tag.report (/Users/jj/.bvm/versions/0.0.603/bit-0.0.603/node_modules/@teambit/workspace/dist/tag-cmd.js:221:21)
    at async CommandRunner.runReportHandler (/Users/jj/.bvm/versions/0.0.603/bit-0.0.603/node_modules/@teambit/cli/dist/command-runner.js:214:20)
    at async CommandRunner.runCommand (/Users/jj/.bvm/versions/0.0.603/bit-0.0.603/node_modules/@teambit/cli/dist/command-runner.js:142:16)
user gets the following error: 
The following errors were found while running the build pipeline
Failed task 1: "teambit.preview/preview:GeneratePreview" of env "teambit.angular/angular-v13@0.0.7"
component: interface-agency.directives/select/option@0.0.4
Module build failed (from ../../node_modules/.pnpm/registry.npmjs.org+@ngtools+webpack@13.1.2_08e2bc1fe65a4145f6802de023172619/node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Symbol CommonModule declared in /Users/jj/Library/Caches/Bit/capsules/c972a01e96c64f7297053d3e723ba557e52f2a3f/node_modules/.pnpm/registry.npmjs.org+@angular+common@13.1.2_@angular+core@13.1.1+rxjs@7.4.0/node_modules/@angular/common/common.d.ts is not exported from @angular/common (import into /Users/jj/Library/Caches/Bit/capsules/c972a01e96c64f7297053d3e723ba557e52f2a3f/interface-agency.directives_select_option@0.0.4/src/module.ts)
    at /Users/jj/Library/Caches/Bit/capsules/ef633dd53bb7108ce727a028846604bfc4e2a63b/node_modules/.pnpm/registry.npmjs.org+@ngtools+webpack@13.1.2_08e2bc1fe65a4145f6802de023172619/node_modules/@ngtools/webpack/src/ivy/loader.js:77:18
Module build failed (from ../../node_modules/.pnpm/registry.npmjs.org+@ngtools+webpack@13.1.2_08e2bc1fe65a4145f6802de023172619/node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Symbol CommonModule declared in /Users/jj/Library/Caches/Bit/capsules/c972a01e96c64f7297053d3e723ba557e52f2a3f/node_modules/.pnpm/registry.npmjs.org+@angular+common@13.1.2_@angular+core@13.1.1+rxjs@7.4.0/node_modules/@angular/common/common.d.ts is not exported from @angular/common (import into /Users/jj/Library/Caches/Bit/capsules/c972a01e96c64f7297053d3e723ba557e52f2a3f/interface-agency.directives_select_option@0.0.4/src/module.ts)
    at /Users/jj/Library/Caches/Bit/capsules/ef633dd53bb7108ce727a028846604bfc4e2a63b/node_modules/.pnpm/registry.npmjs.org+@ngtools+webpack@13.1.2_08e2bc1fe65a4145f6802de023172619/node_modules/@ngtools/webpack/src/ivy/loader.js:77:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Module build failed (from ../../node_modules/.pnpm/registry.npmjs.org+@ngtools+webpack@13.1.2_08e2bc1fe65a4145f6802de023172619/node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Symbol CommonModule declared in /Users/jj/Library/Caches/Bit/capsules/c972a01e96c64f7297053d3e723ba557e52f2a3f/node_modules/.pnpm/registry.npmjs.org+@angular+common@13.1.2_@angular+core@13.1.1+rxjs@7.4.0/node_modules/@angular/common/common.d.ts is not exported from @angular/common (import into /Users/jj/Library/Caches/Bit/capsules/c972a01e96c64f7297053d3e723ba557e52f2a3f/interface-agency.directives_select_option@0.0.4/src/module.ts)
    at /Users/jj/Library/Caches/Bit/capsules/ef633dd53bb7108ce727a028846604bfc4e2a63b/node_modules/.pnpm/registry.npmjs.org+@ngtools+webpack@13.1.2_08e2bc1fe65a4145f6802de023172619/node_modules/@ngtools/webpack/src/ivy/loader.js:77:18
Module build failed (from ../../node_modules/.pnpm/registry.npmjs.org+@ngtools+webpack@13.1.2_08e2bc1fe65a4145f6802de023172619/node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Symbol CommonModule declared in /Users/jj/Library/Caches/Bit/capsules/c972a01e96c64f7297053d3e723ba557e52f2a3f/node_modules/.pnpm/registry.npmjs.org+@angular+common@13.1.2_@angular+core@13.1.1+rxjs@7.4.0/node_modules/@angular/common/common.d.ts is not exported from @angular/common (import into /Users/jj/Library/Caches/Bit/capsules/c972a01e96c64f7297053d3e723ba557e52f2a3f/interface-agency.directives_select_option@0.0.4/src/module.ts)
    at /Users/jj/Library/Caches/Bit/capsules/ef633dd53bb7108ce727a028846604bfc4e2a63b/node_modules/.pnpm/registry.npmjs.org+@ngtools+webpack@13.1.2_08e2bc1fe65a4145f6802de023172619/node_modules/@ngtools/webpack/src/ivy/loader.js:77:18
Module build failed (from ../../node_modules/.pnpm/registry.npmjs.org+@ngtools+webpack@13.1.2_08e2bc1fe65a4145f6802de023172619/node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Symbol CommonModule declared in /Users/jj/Library/Caches/Bit/capsules/c972a01e96c64f7297053d3e723ba557e52f2a3f/node_modules/.pnpm/registry.npmjs.org+@angular+common@13.1.2_@angular+core@13.1.1+rxjs@7.4.0/node_modules/@angular/common/common.d.ts is not exported from @angular/common (import into /Users/jj/Library/Caches/Bit/capsules/c972a01e96c64f7297053d3e723ba557e52f2a3f/interface-agency.directives_select_option@0.0.4/src/module.ts)
    at /Users/jj/Library/Caches/Bit/capsules/ef633dd53bb7108ce727a028846604bfc4e2a63b/node_modules/.pnpm/registry.npmjs.org+@ngtools+webpack@13.1.2_08e2bc1fe65a4145f6802de023172619/node_modules/@ngtools/webpack/src/ivy/loader.js:77:18
Module build failed (from ../../node_modules/.pnpm/registry.npmjs.org+@ngtools+webpack@13.1.2_08e2bc1fe65a4145f6802de023172619/node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Symbol CommonModule declared in /Users/jj/Library/Caches/Bit/capsules/c972a01e96c64f7297053d3e723ba557e52f2a3f/node_modules/.pnpm/registry.npmjs.org+@angular+common@13.1.2_@angular+core@13.1.1+rxjs@7.4.0/node_modules/@angular/common/common.d.ts is not exported from @angular/common (import into /Users/jj/Library/Caches/Bit/capsules/c972a01e96c64f7297053d3e723ba557e52f2a3f/interface-agency.directives_select_option@0.0.4/src/module.ts)
    at /Users/jj/Library/Caches/Bit/capsules/ef633dd53bb7108ce727a028846604bfc4e2a63b/node_modules/.pnpm/registry.npmjs.org+@ngtools+webpack@13.1.2_08e2bc1fe65a4145f6802de023172619/node_modules/@ngtools/webpack/src/ivy/loader.js:77:18
Module build failed (from ../../node_modules/.pnpm/registry.npmjs.org+@ngtools+webpack@13.1.2_08e2bc1fe65a4145f6802de023172619/node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Symbol CommonModule declared in /Users/jj/Library/Caches/Bit/capsules/c972a01e96c64f7297053d3e723ba557e52f2a3f/node_modules/.pnpm/registry.npmjs.org+@angular+common@13.1.2_@angular+core@13.1.1+rxjs@7.4.0/node_modules/@angular/common/common.d.ts is not exported from @angular/common (import into /Users/jj/Library/Caches/Bit/capsules/c972a01e96c64f7297053d3e723ba557e52f2a3f/interface-agency.directives_select_option@0.0.4/src/module.ts)
    at /Users/jj/Library/Caches/Bit/capsules/ef633dd53bb7108ce727a028846604bfc4e2a63b/node_modules/.pnpm/registry.npmjs.org+@ngtools+webpack@13.1.2_08e2bc1fe65a4145f6802de023172619/node_modules/@ngtools/webpack/src/ivy/loader.js:77:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Module build failed (from ../../node_modules/.pnpm/registry.npmjs.org+@ngtools+webpack@13.1.2_08e2bc1fe65a4145f6802de023172619/node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Symbol CommonModule declared in /Users/jj/Library/Caches/Bit/capsules/c972a01e96c64f7297053d3e723ba557e52f2a3f/node_modules/.pnpm/registry.npmjs.org+@angular+common@13.1.2_@angular+core@13.1.1+rxjs@7.4.0/node_modules/@angular/common/common.d.ts is not exported from @angular/common (import into /Users/jj/Library/Caches/Bit/capsules/c972a01e96c64f7297053d3e723ba557e52f2a3f/interface-agency.directives_select_option@0.0.4/src/module.ts)
    at /Users/jj/Library/Caches/Bit/capsules/ef633dd53bb7108ce727a028846604bfc4e2a63b/node_modules/.pnpm/registry.npmjs.org+@ngtools+webpack@13.1.2_08e2bc1fe65a4145f6802de023172619/node_modules/@ngtools/webpack/src/ivy/loader.js:77:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Found 8 errors in 1 components


✖ Total 6 tasks. 5 succeeded. 1 failed. 0 skipped. Total errors: 8.
```

Noticed that in the v13 example, there aren't any directives from the CommonModule being used.

Let me know if there is anything I can do to help! TY

**Comment by ocombe** [comment]
Thanks, trying it now

**Comment by ocombe** [comment]
I tried it with a new project and it works for me.
A few things that are weird in your `bit show`:  `@angular/core` is marked as a dev dependency, and you have `@angular/forms` as a simple dependency. That shouldn't be the case...
Can you send me a zip of your project files (or a github repo) so that I can check what's going on (without node_modules)?
You can join our community slack if you want, it might be easier for you: https://join.slack.com/t/bit-dev-community/shared_invite/zt-o2tim18y-UzwOCFdTafmFKEqm2tXE4w

**Comment by johnjspiteri** [comment]
Thank you for the quick response, appreciate it!

Let me give your directions a try, if I still have issues... would be happy to put together a repo.

Will definitely see you on Slack in the future 👍

**Comment by johnjspiteri** [comment]
@ocombe, was able to start fresh and get everything working... Thank you.

How does this import in a component work..

```
import { AbstractControl, ControlValueAccessor, NG_VALUE_ACCESSOR, NgControl } from '@angular/forms';
```

Without importing the "FormsModule" in the parent module of the component?

**Comment by ocombe** [comment]
Some of the angular modules are loaded in the app that displays the compositions, that includes forms, but you shouldn't rely on it as it would probably break in your app once you import your code.

**Comment by johnjspiteri** [comment]
Good to know... super work, so happy to start using Bit with our Angular projects. Thank you
